schedules:
- cron: '*/10 * * * *'
  displayName: runs every ten minutes
  branches:
    include:
    - feature/schedule-pipeline
  always: 'true'

trigger:
- feature/schedule-pipeline

pool:
  vmImage: ubuntu-latest

stages:
- stage: Development
  jobs:
  - job: Build
    steps:
    - script: python3 external-api.py
      displayName: 'Run Python script'

