schedules:
- cron: '*/10 * * * *'
  displayName: runs every ten minutes
  branches:
    include:
    - feature/schedule-pipeline
  always: 'true'

variables: 
  db_host: ${env:DB_HOST}
  db_name: ${env:DB_NAME}
  db_port: ${env:DB_PORT}
  db_user: ${env:DB_USER}
  db_pass: ${env:DB_PASSWORD}


trigger:
- feature/schedule-pipeline

pool:
  vmImage: ubuntu-latest

stages:
- stage: Development
  jobs:
  - job: Build
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - env:
        DB_HOST: $(db_host)
        DB_NAME: $(db_name)
        DB_PORT: $(db_port)
        DB_USER: $(db_user)
        DB_PASSWORD: $(db_pass)
      script: python3 test.py
      displayName: 'Run Python script'

# resources:
#   pipelines:
#   - pipeline: mainpipeline # Name of the pipeline resource.
#     source: security-lib-ci # The name of the pipeline referenced by this pipeline resource.
#     trigger: 'true' 

