schedules:
- cron: '*/5 * * * *'
  displayName: runs every 5 minutes
  branches:
    include:
    - feature/schedule-pipeline

trigger:
- feature/schedule-pipeline

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Ik vind het echt niet kunnen dat hij het word negerin gebruikt
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

