schedules:
- cron: '*/10 * * * *'
  displayName: runs every ten minutes
  branches:
    include:
    - feature/schedule-pipeline
  always: 'true'

variables: 
  - name: db_host
    value: '${env:DB_HOST}'
  - name: db_name
    value: '${env:DB_NAME}'
  - name: db_port
    value: '25060'
  - name: db_user
    value: '${env:DB_USER}'
  - name: db_pass
    value: '${env:DB_PASSWORD}'


trigger:
- feature/schedule-pipeline

pool:
  vmImage: ubuntu-latest

stages:
- stage: Development
  jobs:
  - job: Build
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: |
        python3 test.py
      env:
        DB_HOST: $[ variables['db_host'] ]
        DB_NAME: $[ variables['db_name'] ]
        DB_PORT: $[ int(variables['db_port']) ]
        DB_USER: $[ variables['db_user'] ]
        DB_PASSWORD: $[ variables['db_pass'] ]
      displayName: 'Run Python script'

# resources:
#   pipelines:
#   - pipeline: mainpipeline # Name of the pipeline resource.
#     source: security-lib-ci # The name of the pipeline referenced by this pipeline resource.
#     trigger: 'true' 

