schedules:
- cron: '10 * * * *'
  displayName: runs every twenty minutes
  branches:
    include:
    - main
    - feature/external-api

trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
