schedules:
- cron: '*/10 * * * *'
  displayName: runs every ten minutes
  branches:
    include:
    - feature/schedule-pipeline
  always: 'true'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Ik vind het echt niet kunnen dat hij het word negerin gebruikt
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

