name: CICD Pipeline
on:
  # workflow_run:
  #   workflows: [Scheduled Pipeline]
  #   types:
  #     - completed
  #   branches:
  #     - feature/cicd-pipeline
  push:
    branches:
      - feature/cicd-pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.x'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
          
      - name: Build Docker container
        run: |
          docker build -t my-cicd-pipeline:latest .
          echo 'dop_v1_ed4d6447a30f8c90c1b3d5af0ca69ee447bf0c968fd663de96d12c3d796f6243' | docker login -u 'olafmajoor@hotmail.com' --password-stdin registry.digitalocean.com
          docker tag my-cicd-pipeline registry.digitalocean.com/container-weerwijzer/my-cicd-pipeline
          docker image push registry.digitalocean.com/container-weerwijzer/my-cicd-pipeline

#      - name: Build Docker image
#        run: docker build --tag my-cicd-pipeline .
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:dop_v1_ed4d6447a30f8c90c1b3d5af0ca69ee447bf0c968fd663de96d12c3d796f6243
#          token: ZG9wX3YxXzFmMDY4MWEwNDZhZjVkOTQyZjIzNmMzM2JjNDBhY2E5Y2Y3MWZiODYzMzkwNDNkNjk4OGNiYTRiODM3ODRhMTQ6ZG9wX3YxXzFmMDY4MWEwNDZhZjVkOTQyZjIzNmMzM2JjNDBhY2E5Y2Y3MWZiODYzMzkwNDNkNjk4OGNiYTRiODM3ODRhMTQ=
##      - name: Login to DigitalOcean Container Registry
##        run:
##          docker login registry.digitalocean.com -u 'olafmajoor@hotmail.com' -p 'dop_v1_ed4d6447a30f8c90c1b3d5af0ca69ee447bf0c968fd663de96d12c3d796f6243'
#      - name: Log in to DO Container Registry
#        run: doctl registry login --expiry-seconds 600
#      - name: Tag image
#        run:
#          docker tag my-cicd-pipeline registry.digitalocean.com/container-weerwijzer/my-cicd-pipeline:latest
#      - name: Push image to DO Container Registry
#        run: docker push push registry.digitalocean.com/container-weerwijzer/my-cicd-pipeline:latest


